### ISSUE TITLE
네이버 카페 애드블락 기능

### ISSUE THREAD

**Issue by hinaple** [wei756/NaverCafe-Addon#33]
![image](https://user-images.githubusercontent.com/55937704/114964750-47bb0580-9eaa-11eb-86cf-e80391db28f1.png)
`AdvertArea` 클래스에 `display: none;`만 추가시키면 깔끔하게 사라질 것 같습니다

**Comment by wei756** [comment]
애드블럭 플러스 플러그인이나 키위브라우저 등 타사에서 이미 대체 가능한 부분이고 
이미 인기글, 좋아요글 표시에 사용되는 api endpoint나 네이버 측 css를 직접 가져다 사용하고 있는 시점에서 
수익에 직접적으로 영향이 가는 광고 차단 기능까지 넣으면 네이버 측에서 민감하게 반응할 가능성이 있기 때문에 반려하게 되었습니다.
